version: '2'

services:
    archy-build-thing:
        container_name: archy-build-thing
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./config:/srv/abt/config
            - /var/run/docker.sock:/var/run/docker.sock
        restart: "no"
        ports:
            - 8080:8080
        depends_on:
            - postgres
    
    postgres:
        container_name: archy-postgres
        image: postgres:17-alpine
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: archery
            POSTGRES_DB: archery
        volumes:
            - ./config/postgres:/var/lib/postgresql/data
        restart: "no"
